r"""Rebuild the checkpoint registry from the checkpoints themselves.

Purpose: ARCHITECTURE.md §12 describes `checkpoints/checkpoint_metadata.json`
as a lightweight model registry — the file that makes a checkpoint
traceable to the code and config that produced it. It was maintained by
hand, so it drifted: after the Phase 4b retrain it still described the
retired Phase 4 run, labelling `best_model.pt` as "epoch 7, R@10 0.2023,
queue enabled" while that path held a queue-disabled epoch-12 checkpoint.
One entry carried metrics marked "extrapolated from trend", which is a
guess sitting in a registry.

This reads each checkpoint's own embedded metadata instead. A registry
that is generated cannot disagree with the files it describes.

Usage:
    python scripts/index_checkpoints.py --checkpoint-dir checkpoints/train

Writes:
    checkpoints/checkpoint_metadata.json

This is an entry-point script, NOT imported by src/vectormind/.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from vectormind.utils.git_info import describe
from vectormind.utils.logging_config import setup_logging

logger = logging.getLogger(__name__)

DESCRIPTION = (
    "Lightweight model registry (ARCHITECTURE.md §12). Generated by "
    "scripts/index_checkpoints.py from each checkpoint's embedded "
    "metadata — do not edit by hand, it will be overwritten."
)

#: Metrics worth surfacing per checkpoint. The full metric dict is in
#: the checkpoint; the registry is an index, not a second copy of it.
REPORTED_METRICS: tuple[str, ...] = (
    "recall@1",
    "recall@5",
    "recall@10",
    "separation",
    "collapsed",
)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Rebuild checkpoint_metadata.json from the checkpoints."
    )
    parser.add_argument(
        "--checkpoint-dir",
        type=str,
        default="checkpoints/train",
        help="Directory of .pt checkpoints to index.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="checkpoints/checkpoint_metadata.json",
        help="Registry file to write.",
    )
    return parser.parse_args()


def read_entry(path: Path) -> dict[str, Any]:
    """Summarize one checkpoint for the registry.

    Args:
        path: Checkpoint file.

    Returns:
        A registry entry. Fields the checkpoint does not carry are
        ``null`` rather than inferred — the previous hand-written
        registry filled a gap with "extrapolated from trend", and a
        guessed metric in a registry is worse than a missing one.

    Raises:
        OSError: If the file cannot be read.
    """
    # weights_only=False: the metadata block holds plain Python objects
    # alongside the tensors, and this file is produced by this project.
    checkpoint = torch.load(path, map_location="cpu", weights_only=False)
    metadata = checkpoint.get("metadata") or {}
    metrics = metadata.get("metrics") or {}

    raw_epoch = checkpoint.get("epoch")
    entry: dict[str, Any] = {
        # Human epoch numbering, matching every document and the
        # epoch_0NN.pt filenames; the checkpoint stores the loop's
        # 0-based index.
        "epoch": raw_epoch + 1 if isinstance(raw_epoch, int) else None,
        "step": checkpoint.get("step"),
        "saved_at": metadata.get("timestamp_iso"),
        "num_params": metadata.get("num_params"),
        "config_hash": metadata.get("config_hash"),
        "git": metadata.get("git"),
        "size_mb": round(path.stat().st_size / (1024**2), 1),
        "queue_size": (checkpoint.get("queue") or {}).get("queue_size"),
    }
    entry["metrics"] = {
        name: metrics.get(name) for name in REPORTED_METRICS if name in metrics
    } or None
    return entry


def main() -> None:
    """Index every checkpoint in the directory and write the registry."""
    args = parse_args()
    setup_logging(level=logging.INFO)

    checkpoint_dir = Path(args.checkpoint_dir)
    if not checkpoint_dir.is_dir():
        raise SystemExit(f"Not a directory: {checkpoint_dir}")

    files = sorted(checkpoint_dir.glob("*.pt"))
    if not files:
        raise SystemExit(f"No checkpoints found in {checkpoint_dir}")

    entries: dict[str, Any] = {}
    for path in files:
        logger.info("Reading %s", path)
        entries[path.as_posix()] = read_entry(path)

    registry = {
        "description": DESCRIPTION,
        "generated_by": "scripts/index_checkpoints.py",
        "generated_at": datetime.now(UTC).isoformat(),
        "generated_from_git": describe(),
        "checkpoints": entries,
    }

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(registry, indent=2), encoding="utf-8", newline="\n"
    )
    logger.info("Wrote %s (%d checkpoints)", output, len(entries))


if __name__ == "__main__":
    main()
